# Generated by Django 5.0.14 on 2026-05-22 23:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("niveau", models.IntegerField()),
                ("abreviation", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["niveau"],
            },
        ),
        migrations.CreateModel(
            name="Ouvrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("date_ordination", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("RETRAITE", "Retraité"),
                            ("SUSPENDU", "Suspendu"),
                            ("DECEDE", "Décédé"),
                        ],
                        default="ACTIF",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ouvriers",
                        to="ouvriers.grade",
                    ),
                ),
                (
                    "paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ouvriers",
                        to="geo.paroisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ouvrier",
                "verbose_name_plural": "Ouvriers",
                "ordering": ["nom", "prenom"],
            },
        ),
    ]
