# Generated by Django 5.0.14 on 2026-07-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ouvriers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ouvrier",
            name="position",
        ),
    ]
