# Generated by Django 5.0.14 on 2026-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouvriers", "0002_remove_ouvrier_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ouvrier",
            name="statut",
            field=models.CharField(
                choices=[("OCCUPE", "Occupé"), ("INOCCUPE", "Inoccupé")],
                default="OCCUPE",
                max_length=10,
            ),
        ),
    ]
