# Generated by Django 5.0.14 on 2026-05-27 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItinerairePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart_lat", models.FloatField(blank=True, null=True)),
                ("depart_lng", models.FloatField(blank=True, null=True)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duree_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arrivee_paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires_comme_arrivee",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "depart_paroisse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itineraires_comme_depart",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires_personnels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinéraire Personnel",
                "verbose_name_plural": "Itinéraires Personnels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfilVisiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("notifications_email", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paroisse_affiliee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membres_affilies",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "region_preferee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visiteurs_preferes",
                        to="geo.regionsynodale",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_visiteur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Visiteur",
                "verbose_name_plural": "Profils Visiteurs",
            },
        ),
        migrations.CreateModel(
            name="ParoisseEnregistree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_personnelle", models.TextField(blank=True)),
                ("enregistree_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enregistrements_visiteurs",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paroisses_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paroisse Enregistrée",
                "verbose_name_plural": "Paroisses Enregistrées",
                "ordering": ["-enregistree_at"],
                "unique_together": {("utilisateur", "paroisse")},
            },
        ),
        migrations.CreateModel(
            name="ParoisseVue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vue_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vues_visiteurs",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paroisses_vues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paroisse Vue",
                "verbose_name_plural": "Paroisses Vues",
                "indexes": [
                    models.Index(
                        fields=["paroisse", "vue_at"],
                        name="visitors_pa_paroiss_823a48_idx",
                    ),
                    models.Index(
                        fields=["utilisateur", "vue_at"],
                        name="visitors_pa_utilisa_067c6c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RechercheHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=300)),
                ("filtres", models.JSONField(blank=True, default=dict)),
                ("resultats_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recherches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recherche Historique",
                "verbose_name_plural": "Recherches Historiques",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "created_at"],
                        name="visitors_re_utilisa_41445d_idx",
                    )
                ],
            },
        ),
    ]
