# Generated by Django 5.0.14 on 2026-06-30 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationCarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_entite",
                    models.CharField(
                        choices=[("paroisse", "Paroisse"), ("oeuvre", "Œuvre")],
                        max_length=20,
                    ),
                ),
                ("entite_id", models.IntegerField()),
                ("vue_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations_carte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Carte",
                "verbose_name_plural": "Consultations Carte",
                "ordering": ["-vue_at"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "vue_at"],
                        name="visitors_co_utilisa_0e24a0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriCarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_entite",
                    models.CharField(
                        choices=[("paroisse", "Paroisse"), ("oeuvre", "Œuvre")],
                        max_length=20,
                    ),
                ),
                ("entite_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoris_carte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favori Carte",
                "verbose_name_plural": "Favoris Carte",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "created_at"],
                        name="visitors_fa_utilisa_574f87_idx",
                    )
                ],
                "unique_together": {("utilisateur", "type_entite", "entite_id")},
            },
        ),
    ]
