# Generated by Django 5.2.4 on 2025-08-31 23:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['region__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('niveau', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_objet', models.CharField(choices=[('paroisse', 'Paroisse'), ('oeuvre', 'Œuvre'), ('ouvrier', 'Ouvrier')], max_length=20)),
                ('objet_id', models.UUIDField()),
                ('ancienne_position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nouvelle_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('raison_changement', models.TextField()),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Position',
                'verbose_name_plural': 'Historiques Positions',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Paroisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(choices=[('paroisse', 'Paroisse'), ('station', 'Station'), ('annexe', 'Annexe')], default='paroisse', max_length=20)),
                ('communiants', models.PositiveIntegerField(default=0)),
                ('non_communiants', models.PositiveIntegerField(default=0)),
                ('ouvriers', models.PositiveIntegerField(default=0)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paroisses', to='cartographie.district')),
            ],
            options={
                'verbose_name': 'Paroisse',
                'verbose_name_plural': 'Paroisses',
                'ordering': ['region__nom', 'district__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_ordination', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('retraite', 'Retraité'), ('suspendu', 'Suspendu'), ('decede', 'Décédé')], default='actif', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('adresse', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvriers', to='cartographie.grade')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvriers_detail', to='cartographie.paroisse')),
            ],
            options={
                'verbose_name': 'Ouvrier',
                'verbose_name_plural': 'Ouvriers',
                'ordering': ['grade__niveau', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Région Synodale',
                'verbose_name_plural': 'Régions Synodales',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='paroisse',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paroisses', to='cartographie.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='cartographie.region'),
        ),
        migrations.CreateModel(
            name='TypeOeuvre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(default='#007bff', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Type d'Œuvre",
                'verbose_name_plural': "Types d'Œuvres",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('paroissial', 'Paroissial'), ('district', 'District'), ('regional', 'Régional'), ('national', 'National')], default='paroissial', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_construction', 'En Construction'), ('suspendue', 'Suspendue'), ('fermee', 'Fermée')], default='active', max_length=20)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('date_inauguration', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='cartographie.paroisse')),
                ('type_oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='cartographie.typeoeuvre')),
            ],
            options={
                'verbose_name': 'Œuvre',
                'verbose_name_plural': 'Œuvres',
                'ordering': ['type_oeuvre__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneInfluence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('rayon_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('population_estimee', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_influence', to='cartographie.paroisse')),
            ],
            options={
                'verbose_name': "Zone d'Influence",
                'verbose_name_plural': "Zones d'Influence",
                'ordering': ['paroisse__nom'],
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('distance_km', models.FloatField()),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('type_transport', models.CharField(choices=[('pied', 'À pied'), ('velo', 'Vélo'), ('moto', 'Moto'), ('voiture', 'Voiture'), ('transport_public', 'Transport Public')], default='voiture', max_length=20)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paroisse_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires_arrivee', to='cartographie.paroisse')),
                ('paroisse_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires_depart', to='cartographie.paroisse')),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['paroisse_depart__nom', 'paroisse_arrivee__nom'],
                'unique_together': {('paroisse_depart', 'paroisse_arrivee', 'type_transport')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='paroisse',
            unique_together={('nom', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('nom', 'region')},
        ),
        migrations.CreateModel(
            name='StatistiqueAnnuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField()),
                ('communiants', models.PositiveIntegerField(default=0)),
                ('non_communiants', models.PositiveIntegerField(default=0)),
                ('baptemes', models.PositiveIntegerField(default=0)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('mariages', models.PositiveIntegerField(default=0)),
                ('deces', models.PositiveIntegerField(default=0)),
                ('offrandes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validee', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='cartographie.paroisse')),
            ],
            options={
                'verbose_name': 'Statistique Annuelle',
                'verbose_name_plural': 'Statistiques Annuelles',
                'ordering': ['-annee', 'paroisse__nom'],
                'unique_together': {('paroisse', 'annee')},
            },
        ),
    ]
