# Generated by Django 5.2.4 on 2025-08-25 09:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paroisses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('scolaire', 'Scolaire'), ('universitaire', 'Universitaire'), ('medicale', 'Médicale'), ('agropastorale', 'Agropastorale'), ('immeuble', 'Immeuble'), ('terrain', 'Terrain'), ('autre', 'Autre')], max_length=30)),
                ('niveau', models.CharField(choices=[('paroissial', 'Paroissial'), ('district', 'District'), ('regional', 'Régional')], max_length=30)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('paroisse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='paroisses.paroisse')),
            ],
            options={
                'verbose_name': 'Œuvre',
                'verbose_name_plural': 'Œuvres',
            },
        ),
    ]
