# Generated by Django 5.2.4 on 2025-09-08 04:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeuvres', '0001_initial'),
        ('paroisses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='region_synodale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='localisation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='paroisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='paroisses.paroisse'),
        ),
    ]
