# Generated by Django 5.0.14 on 2026-05-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatistiqueAnnuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
                ("communiants", models.IntegerField(default=0)),
                ("non_communiants", models.IntegerField(default=0)),
                ("baptemes", models.IntegerField(default=0)),
                ("confirmations", models.IntegerField(default=0)),
                ("mariages", models.IntegerField(default=0)),
                ("deces", models.IntegerField(default=0)),
                (
                    "offrandes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "dimes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("validee", models.BooleanField(default=False)),
                (
                    "paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiques",
                        to="geo.paroisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique Annuelle",
                "verbose_name_plural": "Statistiques Annuelles",
                "ordering": ["-annee", "paroisse"],
                "unique_together": {("paroisse", "annee")},
            },
        ),
    ]
