# Generated by Django 5.0.14 on 2026-05-25 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_statistiqueannuelle"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins_district",
                to="geo.district",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="force_password_change",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="paroisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins_paroisse",
                to="geo.paroisse",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="permissions_custom",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins_region",
                to="geo.regionsynodale",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
