# Generated by Django 5.0.14 on 2026-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_user_scope_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER", "Super Administrateur National"),
                    ("REGION", "Administrateur Régional"),
                    ("DISTRICT", "Administrateur District"),
                    ("PAROISSE", "Administrateur Paroissial"),
                    ("VISITEUR", "Visiteur Authentifié"),
                ],
                default="PAROISSE",
                max_length=10,
            ),
        ),
    ]
