# Generated by Django 5.0.14 on 2026-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("clair", "Clair"), ("sombre", "Sombre")],
                default="clair",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER", "Administrateur Général"),
                    ("REGION", "Administrateur Régional"),
                    ("DISTRICT", "Administrateur District"),
                    ("PAROISSE", "Administrateur Paroissial"),
                    ("VISITEUR", "Visiteur Authentifié"),
                ],
                default="PAROISSE",
                max_length=10,
            ),
        ),
    ]
