# Generated by Django 5.2.16 on 2026-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_avatar_user_theme_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistiqueannuelle",
            name="total_declare",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
