# Generated by Django 5.2.4 on 2025-08-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paroisses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('region_synodale', models.CharField(blank=True, max_length=255, null=True)),
                ('paroisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvriers_set', to='paroisses.paroisse')),
            ],
        ),
    ]
