# Generated by Django 5.2.4 on 2025-08-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvriers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrier',
            name='paroisse',
        ),
        migrations.AddField(
            model_name='ouvrier',
            name='paroisse_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
