# Generated by Django 5.0.14 on 2026-05-22 23:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOeuvre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("SCOLAIRE", "Scolaire"),
                            ("UNIVERSITAIRE", "Universitaire"),
                            ("MEDICALE", "Médicale"),
                            ("AGROPASTORALE", "Agropastorale"),
                            ("IMMEUBLE", "Immeuble"),
                            ("TERRAIN", "Terrain"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("icone", models.CharField(blank=True, max_length=50)),
                ("couleur", models.CharField(default="#16A34A", max_length=7)),
            ],
            options={
                "verbose_name": "Type d'Œuvre",
                "verbose_name_plural": "Types d'Œuvre",
            },
        ),
        migrations.CreateModel(
            name="Oeuvre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("annee_creation", models.IntegerField(blank=True, null=True)),
                ("capacite", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("est_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paroisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oeuvres",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "type_oeuvre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oeuvres",
                        to="oeuvres.typeoeuvre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Œuvre",
                "verbose_name_plural": "Œuvres",
                "ordering": ["paroisse__district__region", "paroisse", "nom"],
            },
        ),
    ]
