# Generated by Django 5.0.14 on 2026-05-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("oeuvres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oeuvre",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeuvres",
                to="geo.district",
            ),
        ),
        migrations.AddField(
            model_name="oeuvre",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeuvres",
                to="geo.regionsynodale",
            ),
        ),
        migrations.AlterField(
            model_name="oeuvre",
            name="paroisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeuvres",
                to="geo.paroisse",
            ),
        ),
    ]
