# Generated by Django 5.0.14 on 2026-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeuvres", "0002_oeuvre_district_oeuvre_region_alter_oeuvre_paroisse"),
    ]

    operations = [
        migrations.AddField(
            model_name="oeuvre",
            name="en_prospection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oeuvre",
            name="nb_personnels",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
