# Generated by Django 5.2.4 on 2025-08-25 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paroisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau', models.CharField(max_length=255)),
                ('region_synodale', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('communiants', models.PositiveIntegerField(default=0)),
                ('non_communiants', models.PositiveIntegerField(default=0)),
                ('ouvriers', models.PositiveIntegerField(default=0)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
        ),
    ]
