# Generated by Django 5.0.14 on 2026-05-22 23:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["region", "nom"],
            },
        ),
        migrations.CreateModel(
            name="RegionSynodale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("population_estimee", models.IntegerField(blank=True, null=True)),
                ("date_creation", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Région Synodale",
                "verbose_name_plural": "Régions Synodales",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="HistoriquePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_objet",
                    models.CharField(
                        choices=[
                            ("paroisse", "Paroisse"),
                            ("ouvrier", "Ouvrier"),
                            ("oeuvre", "Œuvre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objet_id", models.IntegerField()),
                (
                    "ancienne_position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "nouvelle_position",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("raison_changement", models.TextField(blank=True)),
                ("date_changement", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historiques_position",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Position",
                "verbose_name_plural": "Historiques de Position",
                "ordering": ["-date_changement"],
            },
        ),
        migrations.CreateModel(
            name="Paroisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("annee_creation", models.IntegerField(blank=True, null=True)),
                ("est_active", models.BooleanField(default=True)),
                ("nombre_fideles", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paroisses",
                        to="geo.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paroisse",
                "verbose_name_plural": "Paroisses",
                "ordering": ["district__region", "district", "nom"],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="districts",
                to="geo.regionsynodale",
            ),
        ),
        migrations.CreateModel(
            name="ZoneInfluence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("rayon_km", models.FloatField(blank=True, null=True)),
                ("population_estimee", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "paroisse",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_influence",
                        to="geo.paroisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone d'Influence",
                "verbose_name_plural": "Zones d'Influence",
            },
        ),
        migrations.CreateModel(
            name="Itineraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duree_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "type_transport",
                    models.CharField(
                        choices=[
                            ("ROUTE", "Route"),
                            ("PISTE", "Piste"),
                            ("FLUVIAL", "Voie fluviale"),
                            ("MIXTE", "Mixte"),
                        ],
                        default="ROUTE",
                        max_length=10,
                    ),
                ),
                (
                    "difficulte",
                    models.CharField(
                        choices=[
                            ("FACILE", "Facile"),
                            ("MOYEN", "Moyen"),
                            ("DIFFICILE", "Difficile"),
                        ],
                        default="MOYEN",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "paroisse_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires_arrivee",
                        to="geo.paroisse",
                    ),
                ),
                (
                    "paroisse_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires_depart",
                        to="geo.paroisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinéraire",
                "verbose_name_plural": "Itinéraires",
                "unique_together": {("paroisse_depart", "paroisse_arrivee")},
            },
        ),
    ]
