# Generated by Django 5.0.14 on 2026-05-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paroisse",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("PAROISSE", "Paroisse"),
                    ("STATION", "Station"),
                    ("ANNEXE", "Annexe"),
                ],
                default="PAROISSE",
                max_length=10,
            ),
        ),
    ]
