# Generated by Django 5.0.14 on 2026-07-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_add_niveau_to_paroisse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paroisse",
            name="niveau",
        ),
        migrations.AddField(
            model_name="paroisse",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A++", "A++"),
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                    ("C3", "C3"),
                    ("C4", "C4"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
