# Generated by Django 5.0.14 on 2026-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_remove_paroisse_niveau_paroisse_categorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="paroisse",
            name="en_prospection",
            field=models.BooleanField(default=False),
        ),
    ]
