# Generated by Django 5.2.16 on 2026-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_paroisse_en_prospection"),
    ]

    operations = [
        migrations.AddField(
            model_name="paroisse",
            name="cible_offrande",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
